# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f11c43c14fa33e5d55d5155c4abcf2a69a40591f2c3c9f283efe0238b95d90a85a0bf743f17859e565eacd8681205da42b0b67353a415d19cf6ba134c3e62bf

test:
  secret_key_base: b64e92436ee9e32ff4c510b48b090efe20c1dd3ef3d4727539eadd86b67f41475c21079b10c9b19b5367825562105e420100c8c85d428f4ff158cd096fd3b0c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
